//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedCards
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Gender { get; set; }
        public System.DateTime BDay { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public int House { get; set; }
        public string Housing { get; set; }
        public string Flat { get; set; }
        public string Image { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
