//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProjectWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recordings
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public string Doctor { get; set; }
        public string Cabinet { get; set; }
        public System.DateTime VisitDay { get; set; }
        public string VisitTime { get; set; }
        public int UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
